config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'questions#home'
  get '/question', to: 'questions#ask'
  get '/answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

def answer
  params[:question]
end

# If the message is I am going to work, the coach will answer Great!
# If the message has a question mark ? at the end, the coach will answer Silly question, get dressed and go to work!.
# Otherwise the coach will answer I don't care, get dressed and go to work!

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

  def answer
  end
end
# If the message is I am going to work, the coach will answer Great!
# If the message has a question mark ? at the end, the coach will answer Silly question, get dressed and go to work!.
# Otherwise the coach will answer I don't care, get dressed and go to work!

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid Coaching</h1>
<%= params[:question].capitalize %>
<p><em>-You</em></p>
<% question = params[:question] %>
    <% if question.capitalize == 'I am going to work' %>
    <p> Great! </p>
<% elsif question.end_with?('?')%>
    <p> Silly question, get dressed and go to work </p>
<% else %>
  <p> I don't care, get dressed and go to work! </p>
<% end %>
<p><em>-Your Coach</em></p>
<%= link_to "Ask a new question", question_path %>

app/views/questions/ask.html.erb
<h1>Stupid Coaching</h1>
<form action="/answer" method='get'>
<input type="text" name="question" placeholder="Write your question">
<input type="submit" value="Submit">
</form>

app/views/questions/home.html.erb
<h1>Stupid Coaching</h1>
<%= link_to "Ask your coach anything", question_path %>